#!/usr/bin/env python3
"""tools/corrections_index.py -- every retraction in docs/RETRACTED.json, listed in docs/CORRECTIONS.md.

WHY (A326, 2026-10-10). docs/CORRECTIONS.md opens by calling itself "one index for everything this project
has got wrong", and lawless1987.com links it as the correction index. On 2026-10-10 it named 4 of the 44
retractions in docs/RETRACTED.json, and nothing in it was later than 2026-09-27: the curated sections were
written by hand, and adding a retraction never touched them. Every reviewer in that day's peer review
found it. A forgotten step gets a guard where it is forgotten (CLAUDE.md rule 10), so the full list is
now generated from the ledger, between two markers, and test_ci1_corrections_index.py fails while any
retraction is missing from the file or the generated list is out of date.

The curated sections above the markers stay as they are: they say which refutations cost the most. The
generated list says what exists. The ledger stays the record; this only makes the index whole.

    python tools/corrections_index.py           # print the section
    python tools/corrections_index.py --write   # rewrite it in docs/CORRECTIONS.md
    python tools/corrections_index.py --check   # exit 1 when the file is out of date
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEDGER = os.path.join(HERE, "docs", "RETRACTED.json")
INDEX = os.path.join(HERE, "docs", "CORRECTIONS.md")
BEGIN = "<!-- RETRACTIONS-INDEX:BEGIN -- generated by tools/corrections_index.py from docs/RETRACTED.json; edit the ledger, not this list -->"
END = "<!-- RETRACTIONS-INDEX:END -->"
ANCHOR = "## How a retracted claim is stopped from coming back"
MAX_CHARS = 220


def first_sentence(text, limit=MAX_CHARS):
    """The claim's first sentence, on one line, cut at `limit` with an ellipsis. Pipes are escaped for the table."""
    t = re.sub(r"\s+", " ", str(text or "")).strip()
    m = re.match(r"(.+?[.!?])(\s|$)", t)
    s = m.group(1) if m else t
    if len(s) > limit:
        s = s[:limit - 1].rstrip() + "…"
    return s.replace("|", "\\|")


def section(ledger=None):
    d = ledger if ledger is not None else json.load(open(LEDGER, encoding="utf-8"))
    rows = d.get("retractions", [])
    out = [BEGIN, "", "## Every retraction in the ledger (%d)" % len(rows), "",
           "Generated from [`docs/RETRACTED.json`](RETRACTED.json), in the order the retractions were made. Each "
           "row is the claim as it was retracted; the ledger holds what is true instead, the verbatim original "
           "wording, and the patterns that stop it coming back.", "",
           "| id | what was retracted |", "|---|---|"]
    for r in rows:
        out.append("| `%s` | %s |" % (r.get("id", "?"), first_sentence(r.get("claim"))))
    out += ["", END]
    return "\n".join(out)


def render(text, sec):
    """The index with the generated section replaced, or inserted before ANCHOR the first time."""
    if BEGIN in text and END in text:
        a = text.index(BEGIN)
        b = text.index(END) + len(END)
        return text[:a] + sec + text[b:]
    if ANCHOR not in text:
        raise SystemExit("CORRECTIONS.md has neither the markers nor the anchor heading %r" % ANCHOR)
    i = text.index(ANCHOR)
    return text[:i] + sec + "\n\n" + text[i:]


def missing_ids(text, ledger=None):
    d = ledger if ledger is not None else json.load(open(LEDGER, encoding="utf-8"))
    return [r["id"] for r in d.get("retractions", []) if "`%s`" % r["id"] not in text]


def main(argv):
    cur = open(INDEX, encoding="utf-8").read()
    want = render(cur, section())
    if "--write" in argv:
        if want != cur:
            open(INDEX, "w", encoding="utf-8", newline="\n").write(want)
            print("corrections_index: wrote %s" % os.path.relpath(INDEX, HERE))
        else:
            print("corrections_index: already current")
        return 0
    if "--check" in argv:
        miss = missing_ids(cur)
        if want != cur or miss:
            print("corrections_index: OUT OF DATE -- %d retraction(s) not listed%s; run tools/corrections_index.py --write"
                  % (len(miss), (": " + ", ".join(miss[:8])) if miss else ""))
            return 1
        print("corrections_index: current")
        return 0
    print(section())
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
